-- =========================================================================
-- Al Kabeer Trading & Contracting W.L.L. - HR Document Registry Schema
-- Copy and paste this script into your Supabase SQL Editor (supabase.com)
-- =========================================================================

-- 1. Create hr_documents table
CREATE TABLE IF NOT EXISTS public.hr_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "refNo" TEXT UNIQUE NOT NULL,
    "empName" TEXT NOT NULL,
    "empIdNo" TEXT NOT NULL,
    "empTitle" TEXT NOT NULL,
    "empNat" TEXT NOT NULL,
    "salaryString" TEXT NOT NULL,
    "docDate" TEXT NOT NULL,
    "empDoj" TEXT NOT NULL,
    "docType" TEXT NOT NULL,
    "docTypeName" TEXT NOT NULL,
    "status" TEXT DEFAULT 'VERIFIED',
    "company" TEXT DEFAULT 'Al Kabeer Trading & Contracting W.L.L.',
    "crNo" TEXT DEFAULT '184920',
    "establishmentId" TEXT DEFAULT '74/92014',
    "generatedAt" TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.hr_documents ENABLE ROW LEVEL SECURITY;

-- 3. Policy: Allow Public Read Access for Verification Portal
DROP POLICY IF EXISTS "Allow public read access for verification" ON public.hr_documents;
CREATE POLICY "Allow public read access for verification" 
ON public.hr_documents FOR SELECT 
USING (true);

-- 4. Policy: Allow Insert & Update for HR Document Generator
DROP POLICY IF EXISTS "Allow public insert for HR Generator" ON public.hr_documents;
CREATE POLICY "Allow public insert for HR Generator" 
ON public.hr_documents FOR INSERT 
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update for HR Generator" ON public.hr_documents;
CREATE POLICY "Allow public update for HR Generator" 
ON public.hr_documents FOR UPDATE 
USING (true);
